### ISSUE TITLE
Gaps in translation coverage

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#10737]
## Description

The Chinese language pack has 100% coverage so everything that does not display in the UI as translated is a bug:

Remaining:
- ~~`Locals`, `Arguments` and `registers` in debugger (I cannot find them - are those served by the debugger itself? If so, there could be a map on frontend)~~ -> Not coming from JupyterLab code.
- [ ] `Build failed with`, `Build aborted` etc in `builder/index.src`  
  > Will be though to address and is less critical with the wider spread of pre-built extensions
- [ ] do shortcuts (which are handled by lumino) need translation? (there were voices saying that its not needed on CrowdIn)
    ![Screenshot from 2021-07-29 19-16-33](https://user-images.githubusercontent.com/5832902/127544918-c6eb314e-bcda-4357-b522-82be2a2027b8.png)

Done:
- [x] "Show more outputs": https://github.com/jupyterlab/jupyterlab/pull/18021    https://github.com/jupyterlab/jupyterlab/blob/358e470dd7bf37806827b4ad4e2c4c4fb234d1f3/packages/outputarea/src/widget.ts#L1354-L1355
- [x] top-level menu bar is not translated and menus with submenues are not translated (fixed, released in 3.1.8, see #10739)
    ![Screenshot from 2021-07-29 19-16-18](https://user-images.githubusercontent.com/5832902/127544921-65b12cfc-004f-4c82-9139-649371bcc193.png)
- [x] <s>"show last modified column" in file browser</s> new in 3.1, strings updated on CrowdIn on 2021-08-17
    ![Screenshot from 2021-07-29 19-26-57](https://user-images.githubusercontent.com/5832902/127546158-d53c1554-521b-4a12-9c52-979c42333c56.png)
- [x] <s>Merge Cell Below/Above commands</s> new in 3.1, strings uploaded on CrowdIn on 2021-08-17
    ![Screenshot from 2021-07-29 19-27-50](https://user-images.githubusercontent.com/5832902/127546344-06ee0ed7-b273-45ae-9a22-ec809ba933b3.png)
- [x] Kernel status in status bar (fixed in 3.1.6, see #10738)
    ![Screenshot from 2021-07-29 19-29-39](https://user-images.githubusercontent.com/5832902/127546581-267cae98-779c-4a30-9673-6c96340e58b7.png)
- [x] <s>Some menu items are not translated</s> those are new additions in 3.1 (using unicode for ...), strings updated on CrowdIn on 2021-08-17
    ![Screenshot from 2021-07-29 19-32-26](https://user-images.githubusercontent.com/5832902/127546880-92ff4ae2-19df-4a1e-a5f7-c36c89fdba41.png)
- [x] kernel selector - translator is not passed all the way down in the code (released in 3.1.8, see: #10864)
![Screenshot from 2021-07-29 20-19-27](https://user-images.githubusercontent.com/5832902/127552990-6e54c251-f5e4-4530-b6b5-926998b369b2.png)
- [x] kernel selector vol 2 (one more call to `optionForNone` was missed).
- [x] command/edit mode in status bar (released in 3.1.8, see: #10865)
![Screenshot from 2021-08-18 10-18-38](https://user-images.githubusercontent.com/5832902/129874757-ba2946c7-68ad-4883-9629-31599febff28.png)
![Screenshot from 2021-08-18 10-18-00](https://user-images.githubusercontent.com/5832902/129874763-ce2d7163-4ffa-47c6-a78d-3a2c198c36ac.png)
- [x] Advanced Settings Editor titles and descriptions - this will require more extensive changes, including breaking API, and will be included in 4.0 release (fixed in https://github.com/jupyterlab/jupyterlab_server/pull/205 requires users to upgrade `jupyterlab-server` and `jupyter_server`).
- [x] "completed" in "Saving completed" does not get translated (fixed in #10958, released in 3.1.10)
- [x] Debugger is missing some translations that I missed earlier:
   ![Screenshot from 2021-08-31 17-45-15](https://user-images.githubusercontent.com/5832902/131543238-979a50bb-855c-43d0-bb5f-da029c66f8d7.png).
   I do not know hot to handle "Globals". Should it be translated or not?
- [x] context missing for Open With submenu
   ![Screenshot from 2021-09-01 20-10-58](https://user-images.githubusercontent.com/5832902/131731305-33a0354b-a1da-4aed-ac20-8f7ee8e9f976.png)
- [x] [Placeholder in Stdin](https://github.com/jupyterlab/jupyterlab/pull/12502#discussion_r864617462). It requires to pass the translator object to `Notebook.ContentFactory` and then to `Cell.ContentFactory`.

## Context

- JupyterLab version: 3.1

**Comment by krassowski** [comment]
- [ ] Debugger is missing some translations that I missed earlier: ![Screenshot from 2021-08-31 17-45-15](https://user-images.githubusercontent.com/5832902/131543238-979a50bb-855c-43d0-bb5f-da029c66f8d7.png). I do not know hot to handle "Globals". Should it be translated or not?

**Comment by goanpeca** [comment]
> Globals

I think it should, why do you think it should not?

**Comment by krassowski** [comment]
Because it looks like there is some logic conditioned on it, but I am not sure if I interpret it correctly:

https://github.com/jupyterlab/jupyterlab/blob/a38c46183a192ff759e99bbd1cca66686ded2086/packages/debugger/src/service.ts#L290-L296

Any thoughts @JohanMabille?

**Comment by krassowski** [comment]
- [ ] context missing for Open With submenu?
   ![Screenshot from 2021-09-01 20-10-58](https://user-images.githubusercontent.com/5832902/131731305-33a0354b-a1da-4aed-ac20-8f7ee8e9f976.png)

**Comment by JohanMabille** [comment]
@krassowski I think this name should be translated. Although "Globals" is not part of the Debug Adapter Protocol, it has the same purpose as `Locals`, `Arguments`, or `registers`, which are used as name to display in the UI and should be translated.

**Comment by krassowski** [comment]
Thank you! I will translate `Globals`. I did not find `Locals` though.

---

Another translation issue ("Rename %s file" in context menu on tab bar):

- [ ] ![Screenshot from 2021-09-03 21-22-01](https://user-images.githubusercontent.com/5832902/132061777-4eb559f9-8767-41a1-8ba9-a5f29d8eea63.png)

**Comment by fcollonval** [comment]
Update first comment following https://github.com/jupyterlab/jupyterlab/pull/11006

**Comment by fcollonval** [comment]
I'll remove this one from 4.0.0 milestone as most of the translation holes are addressed.

**Comment by krassowski** [comment]
Closing as all but two listed gaps were addressed as of today. The remaining items are:
- builder strings - extracted to https://github.com/jupyterlab/jupyterlab/issues/18109
- shortcuts - it is not obvious that we need to translate them, if someone wants to contribute they are welcome to open an issue and a PR
