### ISSUE TITLE
Meta-issue: links in JupyterLab

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#1442]
The handling of links in JupyterLab is present in multiple places. We have a number of issues where these things are being discussed open, but need a central meta-issue to track where we are at. The focus of this issue is on the interactions and behaviors users should experience rather than on the technical implementation of those things.

User should be able to:

- [ ] Click on a URL/hyperlink in JLab and have the either open the link in a new browser tab or a new JLab dock panel.
- [ ] This should work for hyperlinks that point to URLs outside of JLab (likely open in a new browser tab).
- [ ] This should for hyperlinks that point to notebooks, text files, etc that live within JLab (likely open in a new JLab dock panel).
- [ ] The format of the URLs embedded into notebook documents should not have to be changed for them to work in JLab.
- [ ] Get a URL for any open JLab document, which, which can be use to open that document in the same JLab instance. Not clear if that would be a use query parameter or not. Also not clear if opening that URL would open that document in a clean session or the existing one. I could imagine that both options would be useful at times. 

There may be other usage patterns, but this is a start...

The following older issues captured part of this discussion and have been now closed as duplicate of this current one:

#1434 
#901 
#1075 
#1191

**Comment by afshin** [comment]
cf. https://github.com/jupyterlab/jupyterlab/pull/1191 (Command links plugin)

**Comment by blink1073** [comment]
Note: the first four bullets were addressed by #1565, and the last was moved back to #1075.
