### ISSUE TITLE
Post 4.0 checklist

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#14549]
Keeping track of tasks to be done after the `4.0` release:

- [x] Make ReadTheDocs `stable` point to ~`main`~ `4.0.x`: https://github.com/jupyterlab/jupyterlab/issues/14549#issuecomment-1568406000
- [x] Default the extension cookiecutter branch to `4.0`: https://github.com/jupyterlab/extension-cookiecutter-ts/
- [x] Update https://github.com/jupyterlab/extension-template: https://github.com/jupyterlab/extension-template/pull/10
- [x] Update Notebook 7: https://github.com/jupyter/notebook/pull/6871
- [x] Jupyter Widgets: https://github.com/jupyter-widgets/ipywidgets/pull/3752
- [x] 4.0 announcement blog post: https://github.com/jupyterlab/team-compass/issues/194

**Comment by jtpio** [comment]
> Do we know why @jupyterlab/celltags is stuck at 4.0.0-alpha.20?

Looks like it was removed according to the extension migration guide:

![image](https://github.com/jupyterlab/jupyterlab/assets/591645/0f7d0773-d0da-40ba-a7e3-109f10a27d03)

(also noticed in https://github.com/jupyter/notebook/pull/6871)

So probably we could update that line and / or the script that adds it to `dev_mode/package.json`.

**Comment by jtpio** [comment]
>     * [ ]  Make ReadTheDocs `stable` point to `main`

If someone knows how to tell ReadTheDocs to point `stable` to `main` instead of `3.6.x` that would be great!

![image](https://github.com/jupyterlab/jupyterlab/assets/591645/25c0cb2a-625c-4e26-b3ef-6e9f6264f851)

**Comment by krassowski** [comment]
I think this is under `Advanced Settings` → `Default branch`:

![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/14c51080-4a0b-4f5e-9944-e8fe5bd193b2)

but I do not have access to jupyterlab RTD

**Comment by seibert** [comment]
I was just looking at this and wondering why 4.0.x is not listed as one of the docs versions.  Does that need to appear before you can set "stable" to point at a new version?

**Comment by krassowski** [comment]
It looks like RTD has an issue (or we have it misconfigured?) with fetching all tags for our repo (granted we have **many** tags) and only sees the branches. Since we have not branched 4.0 out of main yet, there is no branch to point too.

**Comment by jtpio** [comment]
Closing as most items listed in the first comment have been addressed.

Jupyter Widgets support is tracked in https://github.com/jupyter-widgets/ipywidgets/pull/3752.

Thanks all!
