### ISSUE TITLE
LSP follow-up checklist

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#14711]
This is a running checklist for things noted when porting jupyterlab-lsp extension:

- [x] there does not seem to be a way to add extension conditionally on editor type (see also https://github.com/jupyterlab/jupyterlab/issues/14710).
- [x] we could probably remove `packages/lsp/src/adapters/statusmessage.ts`
- [x] `ILSPDocumentConnectionManager` may need to expose:
  - `initialConfigurations`
  - `updateLogging`
- [x] the plugin providing `ILSPDocumentConnectionManager` should be separate from plugin providing settings/running tab integration
- [ ] `ILanguageServerManager` needs to expose `specs` → maybe we can just use `getMatchingSpecs()` with no args
- [ ] `VirtualDocuments` may need to expose `virtualLines` (currently protected) - or maybe not, maybe we just need a method which gets indices of cells covered by it (the only substantial donwstream usage is in `getBreadcrumbs`).
- [x] `ILSPConnection` needs to expose:
   - `serverCapabilities`
   - `provides()` (or remove it as redundant to `serverCapabilities`)

**Comment by trungleduc** [comment]
Thanks @krassowski for working on the LSP. My lack of experience with the LSP extension has caused many regressions in the integration PR. I will keep following your work and please let me know if I can join the effort on some parts

**Comment by krassowski** [comment]
It is difficult to get from CodeMirror's `EditorView` to `CodeEditor.IEditor` and `Document.IEditor`. The latter used to be synonymous with the  former but due to windowed notebook refactor an accesor wrapper was created as follows in https://github.com/jupyterlab/jupyterlab/pull/12554:

https://github.com/jupyterlab/jupyterlab/blob/42fb46470fb747ec1a8e6ad9a32ed11a0d4991a7/packages/lsp/src/tokens.ts#L179-L228

Worst case scenario, I could workaround this using the fact that the `factory` of `editorExtensionRegistry.addExtension` includes `CodeEditor.IModel`:

```ts
const editor = adapter.editors.find(e => e.model === options.model);
```

but neither `Document.ICodeBlockOptions` nor `Document.IEditor` expose the model.

1. Can we expose the model? If we did, we could remove `value` string which I think may not be needed on the public interface if the model is available. 
2. Is there a better way to get the `Document.IEditor` for an event invoked within CodeMirror extension?

Please note that using `adapter.activeEditor` is only appropriate for responding to user events such as typing or mouse click, because:
- when mouse moves (e.g. hover) it may move over another cell - `activeEditor` is not pointing to the target
- on RTC when we want to update highlights based on text typed by another user, the current's user `activeEditor` is not relevant.

**Comment by hbcarlos** [comment]
Hi @krassowski. I'm not sure I understand what you are trying to achive.

> It is difficult to get from CodeMirror's EditorView to CodeEditor.IEditor and Document.IEditor. The latter used to be synonymous with the former but due to windowed notebook refactor an accesor wrapper was created as follows in https://github.com/jupyterlab/jupyterlab/pull/12554:

Could you point me to the jupyterlab-lsp where you are facing this issue? I need some context.

> Worst case scenario, I could workaround this using the fact that the factory of editorExtensionRegistry.addExtension includes CodeEditor.IModel:
>
> `const editor = adapter.editors.find(e => e.model === options.model);`
>
> but neither Document.ICodeBlockOptions nor Document.IEditor expose the model.
>
>    1. Can we expose the model? If we did, we could remove value string which I think may not be needed on the public interface if the model is available.
>    2. Is there a better way to get the Document.IEditor for an event invoked within CodeMirror extension?
If the goal is to access the `CodeEditor.IModel`, the `CodeEditor.IEditor` includes the model.

You could do something like the following:
```ts
const editor: Document.IEditor;
const model: CodeEditor.IModel = editor.getEditor()?.model;
```

**Comment by krassowski** [comment]
> You could do something like the following:
> ```ts
> const editor: Document.IEditor;
> const model: CodeEditor.IModel = editor.getEditor()?.model;
> ```

When using `editorExtensionRegistry.addExtension` there is no `Document.IEditor`, only `EditorView` and `CodeEditor.IModel`. Have a look at how `adapter` and `Document.IEditor` are obtained in https://github.com/jupyter-lsp/jupyterlab-lsp/pull/949 - there are comments explaining edge cases when current implementation will fail:
-  `packages/jupyterlab-lsp/src/features/signature.ts`,
- `packages/jupyterlab-lsp/src/features/syntax_highlighting.ts`
- `packages/jupyterlab-lsp/src/features/diagnostics/feature.ts`

**Comment by hbcarlos** [comment]
Thank Michal, I see the problem now.

One way would be what you described above, using the model from the `factory`. Nevertheless, I'm not sure what is the best solution. @fcollonval may know more about CodeMirror.

**Comment by krassowski** [comment]
Closing as the discussed improvements were largely applied and the remaining ones have alternative solutions.
