### ISSUE TITLE
Issue Triage Checklist

### ISSUE THREAD

**Issue by richagadgil** [jupyterlab/jupyterlab#5726]
Hi, below I have posted a suggested issue triage checklist created by Brian and myself. This checklist was inspired by the book the Checklist Manifesto. The book discusses how checklists have been created to manage complexity, communication, and human error in highly technical fields like construction, medicine, and law. It also specifies how good checklists can be short, concise, and effective. 

The checklist below serves to establish a point of communication between the JupyterLab team and the contributor, provide information about the issue, categorize the issue, and prepare the issue for further development. 

- [ ] Introduce yourself and thank the person. Let them know the issue was received. 
- [ ] Check that all issue template information has been provided.
- [ ] Assign one type label (bug, enhancement, feedback, maintenance, question) to the issue. 
- [ ] Label the issue using the package, status, and tag categories.
- [ ] Target the issue to the appropriate milestone. 
- [ ] Tag relevant people if necessary.

@ellisonbg

**Comment by ellisonbg** [comment]
@richagadgil thanks for working on this. I should mention that this checklist more or less encodes our current best practice, with the goal to make it easy for us to scale up the triage activity to new people who want to help out in this area.

I am a strong +1 on the content of the checklist, my main question is how we want to use it in practice.

**Comment by ellisonbg** [comment]
In the team meeting we talked about creating a GitHub bot that would add this checklist as the first comment to each issue/PR that is opened. @richagadgil is going to begin exploring that.

**Comment by richagadgil** [comment]
Just to follow up on this, Probot is a framework to build apps for Github. The probot repo contains an autoresponder tool which would be useful for auto-generating this triage checklist once an issue has been opened.

https://github.com/probot/autoresponder

**Comment by Zsailer** [comment]
I think "roles" like this should be defined on one of Jupyter's main documentation pages. "Issue Triager" is a role that generalizes to many of Jupyter's subprojects. Adding this checklist to a documentation page would be helpful for someone new to the community who wants to know how they can contribute.

Maybe Jupyter's ["Contributor Guides"](https://jupyter.readthedocs.io/en/latest/contributor/content-contributor.html# ) documentation is a good home?

**Comment by jweill-aws** [comment]
Closing in favor of #11660 which was resolved by #11661.
