### ISSUE TITLE
Pull Request Checklist 

### ISSUE THREAD

**Issue by richagadgil** [jupyterlab/jupyterlab#6170]
Hi, below I have posted a suggested pull request checklist. 
The checklist below serves to ensure pull request descriptions address 'why, what, and how' they were created. This would be useful to ensure pull requests are directed towards existing issues and provide a complete description. 

I welcome any feedback on this!

- [ ] Note what issue(s) this pull request addresses. [Please look through open pull requests to see if someone has already started working on this.] We strongly encourage the community to open an issue describing proposed work before opening a pull request.
- [ ] Provide a detailed description of the pull request. Why are these changes necessary? How have they been implemented?
- [ ] For UI/UX changes, include before/after screenshots and a narrative description of visual or user interaction changes. How does your design effectively address the problem? 
- [ ] Provide a list of Jupyterlab packages the pull request modifies.
- [ ] Describe any backwards incompatible changes to Jupyterlab’s public APIs.

@ellisonbg

**Comment by vidartf** [comment]
Sounds useful! As far as I can tell, this differs from #5726, in that this is a list for the submitter to use. If that is correct, then you are more than welcome to open a PR to add this to the [PR template](https://github.com/jupyterlab/jupyterlab/blob/master/.github/pull_request_template.md). I'm not sure which format is best:
- Encourage the user to leave it in place (at the bottom?) of the PR post.
- Encourage the user to delete these points before posting.
Or maybe we just let the user decide 🤷‍♂️

**Comment by Zsailer** [comment]
A couple of the checklist items have multiple "actionable" steps in a single point. I would suggest breaking these into multiple points. Here's a revised version. What do you think?

- [ ] Note what issue(s) this pull request addresses. (We strongly encourage the community to open an issue describing proposed work before opening a pull request.)
- [ ] Look through open pull requests to see if someone has already started working on this. 
- [ ] Provide a detailed description of the pull request. (Why are these changes necessary? How have they been implemented?)
- [ ] For UI/UX changes, include before/after screenshots.
- [ ] Include a narrative description of visual or user interaction changes. (How does your design effectively address the problem?)
- [ ] Provide a list of Jupyterlab packages the pull request modifies.
- [ ] Describe any backwards incompatible changes to Jupyterlab’s public APIs.

**Comment by vidartf** [comment]
Closed in #6182.
