### ISSUE TITLE
TODO/Deprecations for 2.0

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#7720]
Searching the code base for [TODO items](https://github.com/jupyterlab/jupyterlab/search?q=TODO&unscoped_q=TODO) or [deprecations](https://github.com/jupyterlab/jupyterlab/search?p=1&q=deprecated&unscoped_q=deprecated), I see some interesting possibilities:

I put each reference below in a checklist so that we can check off when we have examined it, and we can add a note or reference to an issue if we are solving it now.

## Notes about TODO items
- [x] https://github.com/jupyterlab/jupyterlab/blob/72d9e17dadbd8c9e9869c863949e44b57a80120d/packages/filebrowser/src/listing.ts#L1811
- [x] https://github.com/jupyterlab/jupyterlab/blob/735dffc6ef2cf9f3356f5bd862bb0bbfaec249ac/jupyterlab/handlers/extension_manager_handler.py#L70
- [ ] https://github.com/jupyterlab/jupyterlab/blob/735dffc6ef2cf9f3356f5bd862bb0bbfaec249ac/jupyterlab/handlers/extension_manager_handler.py#L89
- [x] https://github.com/jupyterlab/jupyterlab/blob/6bc9df517adeecc4533698b98ae97aedf329e2db/packages/statusbar/src/deprecated.tsx#L8
- [x] https://github.com/jupyterlab/jupyterlab/blob/735dffc6ef2cf9f3356f5bd862bb0bbfaec249ac/jupyterlab/handlers/build_handler.py#L25
- [x] https://github.com/jupyterlab/jupyterlab/blob/3d1e5ee94a2df3978018fe632217ad8a66675e28/jupyterlab/extension.py#L148
- [x] https://github.com/jupyterlab/jupyterlab/blob/7fb018558f9c812e3e2a3355fb6ab7c1a30486d8/packages/settingeditor/src/plugineditor.ts#L48
- [x] https://github.com/jupyterlab/jupyterlab/blob/72d9e17dadbd8c9e9869c863949e44b57a80120d/packages/notebook/src/panel.ts#L166
- [x] https://github.com/jupyterlab/jupyterlab/blob/dfeaf98cf39acacf7ed1984d916c1a75e51052d8/packages/services/src/terminal/manager.ts#L222
- [ ] https://github.com/jupyterlab/jupyterlab/blob/7fb018558f9c812e3e2a3355fb6ab7c1a30486d8/packages/codemirror-extension/src/index.ts#L351
- [x] https://github.com/jupyterlab/jupyterlab/blob/dfeaf98cf39acacf7ed1984d916c1a75e51052d8/packages/services/src/kernel/manager.ts#L250
- [x] https://github.com/jupyterlab/jupyterlab/blob/dfeaf98cf39acacf7ed1984d916c1a75e51052d8/packages/services/src/session/manager.ts#L260
- [ ] https://github.com/jupyterlab/jupyterlab/blob/7fb018558f9c812e3e2a3355fb6ab7c1a30486d8/packages/apputils/src/thememanager.ts#L288
- [ ] https://github.com/jupyterlab/jupyterlab/blob/72d9e17dadbd8c9e9869c863949e44b57a80120d/packages/apputils/src/dialog.ts#L68
- [ ] https://github.com/jupyterlab/jupyterlab/blob/72d9e17dadbd8c9e9869c863949e44b57a80120d/packages/apputils/src/dialog.ts#L68
- [ ] https://github.com/jupyterlab/jupyterlab/blob/1fc7a3da90e7860ece1394944e59dde677b79a56/packages/console-extension/src/index.ts#L358

## Notes about deprecations
- [x] https://github.com/jupyterlab/jupyterlab/blob/3d710e0a26bee56fa0a008ecd547e9f663ae6340/jupyterlab/labhubapp.py#L35
- [x] https://github.com/jupyterlab/jupyterlab/blob/7fb018558f9c812e3e2a3355fb6ab7c1a30486d8/packages/services/src/kernel/messages.ts#L135-L138
- [x] https://github.com/jupyterlab/jupyterlab/blob/f2d664b341045876626af2785d9a222dd0e9c794/tests/test-services/src/kernel/messages.spec.ts#L173
- [x] https://github.com/jupyterlab/jupyterlab/blob/3755447bb7420c9d78642ca16dfcb13c55339613/packages/rendermime/src/factories.ts#L74
- [x] https://github.com/jupyterlab/jupyterlab/blob/72d9e17dadbd8c9e9869c863949e44b57a80120d/packages/rendermime/src/widgets.ts#L382
- [x] https://github.com/jupyterlab/jupyterlab/blob/5e68c8aa72f2f04a036b06dafe7029995e496d06/jupyterlab/commands.py#L347-L364
- [x] https://github.com/jupyterlab/jupyterlab/blob/47de94a1167a532da92b37285fcd1c9f717393a0/scripts/ci_script.sh#L196

**Comment by jasongrout** [comment]
@blink1073 - here are some possibly api-breaking changes we've held off on for 2.0. Do you (or anyone else) have time to look at these to decide whether we really want to do them for 2.0?

**Comment by blink1073** [comment]
I'm making a PR now, checking off items as I address them.

**Comment by telamonian** [comment]
I checked off the one from `jupyterlab/packages/filebrowser/src/listing.ts`, that's handled by #7700. I'll probably also handle deleting `jupyterlab/packages/statusbar/src/deprecated.tsx` in that same PR

**Comment by blink1073** [comment]
I already removed `jupyterlab/packages/statusbar/src/deprecated.tsx` in my branch.

**Comment by jasongrout** [comment]
I should add here that I looked at the TODO and deprecation search results linked above and tried to filter them for 2.0-relevant issues. If someone has time to look at the full list of search results to double-check that I didn't miss anything relevant, that would be great.

**Comment by blink1073** [comment]
@telamonian, I see that you would pick up merge conflicts in #7700 if I remove `deprecated.tsx`, I'll restore it here.

**Comment by blink1073** [comment]
Closing as addressed by #7724 and #7700, at least as far as 2.0-readiness is concerned.
