### ISSUE TITLE
Side effects after migration to Jupyter Server

### ISSUE THREAD

**Issue by echarles** [jupyterlab/jupyterlab#8856]
I open this issue to track down any side effect further to the merge of https://github.com/jupyterlab/jupyterlab/pull/7416 which makes JupyterLab run on [Jupyter Server](https://github.com/jupyter/jupyter_server). So far:

- [x] Check `base_url` server config (for now 404 for a base_url different from '/') (see https://github.com/jupyter/jupyter_server/issues/278 https://github.com/jupyter/jupyter_server/issues/282)
- [x] Check if `fullStaticUrl` is updated in PageConfig
- [x] Check if publicPath is correctly updated (see https://github.com/jupyterlab/jupyterlab/pull/8845) ?
- [x] [favicon missing in jlab3](https://github.com/jupyterlab/jupyterlab/issues/8794) (see https://github.com/jupyter/jupyter_server/issues/279 https://github.com/jupyter/jupyter_server/issues/283)
- [x] [App version is not properly handled](https://github.com/jupyterlab/jupyterlab/issues/8812)
- [x] Workspace clone (maybe linked to above and/or single mode document?)
- [x] Change `https://jupyter-notebook.readthedocs.io/en/latest/security.html`
- [ ] repo2docker?

**Comment by echarles** [comment]
For `base_url`, I have opened https://github.com/jupyter/jupyter_server/issues/278

**Comment by echarles** [comment]
For the last week broken workspace cloning, this now works back in master. It works in `dev` mode only, because of https://github.com/jupyterlab/jupyterlab/pull/8845#issuecomment-677476040 (cc/ @goanpeca @jasongrout)

**Comment by Zsailer** [comment]
* We've address the `base_url`  and `fullStaticUrl` issue in jupyterlab/jupyterlab_server#120

**Comment by echarles** [comment]
For Lab, `base_url` is addressed in https://github.com/jupyterlab/jupyterlab/pull/8910

**Comment by blink1073** [comment]
I'm still seeing this in JupyterLab `master` as of this morning: 404 GET /static/favicons/favicon.ico (::1) 94.72ms referer=None

**Comment by blink1073** [comment]
With `jupyter_server-1.0.0rc11` the favicon appears!

**Comment by echarles** [comment]
https://github.com/jupyterlab/jupyterlab/pull/8954 opened for the link to jupyter_server RTD.

**Comment by vidartf** [comment]
Is there still something to do here? :)

**Comment by echarles** [comment]
I think this can be close now. There has been other sideeffect for binder I believe, but have been resolved. I will close it. If any issue arise, they be opened anyway 👍
